language: node_js
node_js:
  - "0.11"
  - "0.12"
  - "iojs"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
notifications:
  email: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script:
  - npm run bower
  - npm run test
  - npm run travis
